export const storeProducts=[
    {

    id:1,
    title: "Leagoo Leagoo",
    img: "img/product-1.png",
    price: 120,
    company: "Leagoo",
    info:"Leagoo Leagoo T5 5.5'' FHD Dual Rear Cameras Fingerprint 4GB RAM 64GB ROM MTK6750T Octa-Core 4G Smartphone (Elegance Black) Unlock Phones:Yes Language:Norwegian,Italian,French,German,Russian,Spanish,Polish,English Front Camera Quantity:1 Display Size:5.5 Operation System:Android Phone Type:Smart Phones",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 2,
    title: "samusung s7",
    img:"img/product-2.png",
    price: 16,
    company:"samsung S8",
    info:"",
    inCart: false,
    count: 0,
    total: 0

    
},
{
    id: 3,
    title: "Sony Xperia XA1 -5",
    img:"img/product-3.png",
    price: 160,
    company:"Sony",
    info:"Sony Xperia XA1 - 5 32GB Dual SIM - 23MP Camera - Pink Xperia XA1 boasts a 23MP camera with Exmor RS™ for mobile sensor and F2.0 lens. 8MP Front Camera 5 HD Display Corning Gorilla Glass",
    inCart: false,
    count: 0,
    total: 0
},
{
id:4,
title: "Tecno Camon iClick",
img:"img/product-4.png",
price: 167,
company:"Tecno",
info:"Tecno Camon iClick (20MP Front + 16MP Rear Camera) 4GB RAM + 64GB (Gold) 20MP Front Camera ; Video ChatFlash. 16MP Rear Camera ; Fingerprint Censor & Face Unlock Feature Full View Display; FM Radio ; 4GB RAM GSM 850/900/1800/1900 battery 3750 mAh 12+1 month warranty provided by the manufacturer from date of purchase Android 8.1",
inCart: false,
    count: 0,
    total: 0,
},
{
    id: 5,
    title: "Nokia 1",
    img:"img/product-5.png",
    price: 55,
    company:"nokia",
    info:"Nokia 1 (Dark Blue, 8 GB)  (1 GB RAM)|Expandable Upto 128 GB 11.43 cm (4.5 inch) Display 5MP Rear Camera | 2MP Front Camera 2150 mAh Battery MT6737M Quad Core 1.1 GHz Processor",
    inCart: false,
    count: 0,
    total: 0
},
{
    id:6,
    title: "Tecno F1-5",
    img:"img/product-6.png",
    price: 50,
    company:"tecno",
    info:"Tecno F1 - 5 - 8GB Rom - 1GB Ram - Dual Sim - Champagne Gold OS: HIOS based on Android 8.0 Oreo (Go Edition) SIM Type: Dual Micro SIM 4G LTE: No Screen Size : 5.0″ FWVGA Screen Resolution: 854×480 pixels Processor Type: Quad-core 1.30 GHz RAM: 1GB RAM Internal Storage: 8GB External Storage: MICRO SD up to 32GB Back / Rear Camera: 5MP with dual flash Front Camera: 2MP with Flashlight Battery: 2000 mAh",
     inCart: false,
    count: 0,
    total: 0
},
{
    id: 7,
    title: "iphone XR",
    img:"img/product-7.png",
    price: 1216,
    company:"tecno",
    info:"Apple iPhone XR (Red 256GB ROM) 6.1 Inch Screen 6.1-inch Retina display (LCD) IP67 water and dust resistant (maximum depth of 1 meter up to 30 minutes) 12MP camera with OIS and 7MP True Depth front camera—Portrait mode, Portrait Lighting, Depth Control, and Smart HDR Face ID for secure authentication and Apple Pay A12 Bionic with next-generation Neural Engine Wireless charging—works with Qi chargers iOS 12 with Memoji, Screen Time, Siri Shortcuts, and Group FaceTime",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 8,
    title: "Apple iphone XR",
    img:"img/product-8.png",
    price: 1073,
    company:"Apple",
    info:" Apple iPhone XR (Yellow 128GB ROM) 6.1 Inch Screen 6.1-inch Retina display (LCD) IP67 water and dust resistant (maximum depth of 1 meter up to 30 minutes) 12MP camera with OIS and 7MP True Depth front camera—Portrait mode, Portrait Lighting, Depth Control, and Smart HDR Face ID for secure authentication and Apple Pay A12 Bionic with next-generation Neural Engine Wireless charging—works with Qi chargers iOS 12 with Memoji, Screen Time, Siri Shortcuts, and Group FaceTime",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 9,
    title: "huawei Pro 30",
    img:"img/product-9.png",
    price: 16,
    company:"huawei",
    info:"Generic 5D Curved Edge Tempered Glass For Huawei P30 pro Case Screen Protector On For Huawei P30 Lite Light P 30 P30pro Protective Film Type:Fitted Case Size:For huawei hauwei huawey huawe p30 pro lite light p 30lite 30pro glass Retail Package:No Compatible",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 10,
    title: "huawei p30 pro ",
    img:"img/product-10.png",
    price: 1068,
    company:"huawei",
    info:"Huawei P30 Pro, 6.47, 256GB + 8GB (Dual SIM), Black Display: 6.47 FHD+ (2340*1080p) display, OLED Screen, CPU: Hisilicon Kirin 980 Octa Core EMUI9.1.0 Android 9.0 OS, Memory: 8GB RAM + 256GB ROM ront camera: 32.0MP,Four rear cameras: 40.0MP+20.0MP+8.0MP+Time-of-Flight(TOF) Camera",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 11,
    title: "huawei Y6",
    img:"img/product-11.png",
    price: 16,
    company:"huawei",
    info:"HUAWEI Y6 Prime 2019 - 6.09” - 32GB ROM - 2GB RAM - Dual Sim Display: 6.09” HD+ (1560 x 720) Operating system: Android 9 pie Memory: 2GB RAM + 32GB RAM Rear Camera: 13 M AF Camera, f/1.8 Front Camera: 8 MP FF Camera, Selfie Toning Flash 2.0 Battery: 3020 mAh (Typical value) Earphones Not Included Warranty: 1 Year",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 12,
    title: "huawei y7",
    img:"img/product-12.png",
    price: 16,
    company:"huawei",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 13,
    title: "iphone x",
    img:"img/product-13.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 14,
    title: "iphone x",
    img:"img/product-14.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 15,
    title: "iphone x",
    img:"img/product-15.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 16,
    title: "iphone x",
    img:"img/product-16.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 17,
    title: "iphone x",
    img:"img/product-17.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 18,
    title: "iphone x",
    img:"img/product-18.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 19,
    title: "iphone x",
    img:"img/product-19.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 20,
    title: "iphone x",
    img:"img/product-20.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 21,
    title: "iphone x",
    img:"img/product-21.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 22,
    title: "iphone x",
    img:"img/product-22.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 23,
    title: "iphone x",
    img:"img/product-23.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 24,
    title: "iphone x",
    img:"img/product-24.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 25,
    title: "iphone x",
    img:"img/product-25.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 26,
    title: "iphone x",
    img:"img/product-26.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 27,
    title: "iphone x",
    img:"img/product-27.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 28,
    title: "iphone x",
    img:"img/product-28.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 29,
    title: "iphone x",
    img:"img/product-29.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 30,
    title: "iphone x",
    img:"img/product-30.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 31,
    title: "iphone x",
    img:"img/product-31.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 32,
    title: "iphone x",
    img:"img/product-32.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
id: 33,
title: "iphone x",
img:"img/product-33.png",
price: 10,
company:"apple",
info:"",
inCart: false,
count: 0,
total: 0
},
{
    id: 34,
    title: "iphone x",
    img:"img/product-34.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 35,
    title: "iphone x",
    img:"img/product-35.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 36,
    title: "iphone x",
    img:"img/product-36.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 37,
    title: "iphone x",
    img:"img/product-37.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 38,
    title: "iphone x",
    img:"img/product-38.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 38,
    title: "iphone x",
    img:"img/product-38.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 39,
    title: "iphone x",
    img:"img/product-39.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 40,
    title: "iphone x",
    img:"img/product-40.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 41,
    title: "iphone x",
    img:"img/product-41.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 42,
    title: "iphone x",
    img:"img/product-42.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 43,
    title: "iphone x",
    img:"img/product-43.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 44,
    title: "iphone x",
    img:"img/product-44.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 45,
    title: "iphone x",
    img:"img/product-45.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 46,
    title: "iphone x",
    img:"img/product-46.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 47,
    title: "iphone x",
    img:"img/product-47.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 48,
    title: "iphone x",
    img:"img/product-48.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},

{
    id: 49,
    title: "iphone x",
    img:"img/product-49.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 50,
    title: "iphone x",
    img:"img/product-50.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 51,
    title: "iphone x",
    img:"img/product-51.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 52,
    title: "iphone x",
    img:"img/product-52.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 53,
    title: "iphone x",
    img:"img/product-53.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 54,
    title: "iphone x",
    img:"img/product-54.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 55,
    title: "iphone x",
    img:"img/product-55.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 56,
    title: "iphone x",
    img:"img/product-56.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 57,
    title: "iphone x",
    img:"img/product-57.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 58,
    title: "iphone x",
    img:"img/product-58.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 59,
    title: "iphone x",
    img:"img/product-59.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 60,
    title: "iphone x",
    img:"img/product-60.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 61,
    title: "iphone x",
    img:"img/product-61.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 62,
    title: "iphone 6",
    img:"img/product-62.png",
    price: 160,
    company:"apple",
    info:"Apple  iPhone 6 4.7-Inch Fingerprint(1GB, 64GB ROM) 8MP+7MP – Grey 6.9mm slim, 129g of weight 4.7 inch 1334 x 750 pixel resolution LED backlit IPS LCD, capacitive touchscre Apple iOS 8, upgradable to iOS10.3.2 Dual core 1.4 GHz Apple A8 chipset, M8 motion co-processor, PowerVR GX",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 63,
    title: "iphone x",
    img:"img/product-63.png",
    price: 1160,
    company:"apple",
    info:"Apple IPhone X - 5.8'' - 3GB RAM + 64GB ROM - (12MP + 12MP) + 7MP Smartphone - White  5.8 inch HD Retina Display CPU: A11 Bionic Chip with 64-bit architecture Operation system: iOS 11 Battery: 2716mAh, up to 21 hours talk time",
    inCart: false,
    count: 0,
    total: 0
}
];
export const detailProduct = {
    id: 1,
    title: "HTC-HOT ",
    img: "img/product-23.png",
    price: 17,
    company: "",
    info: "",
    incart: false,
    count: 0,
    total: 0
};


