export const storeProducts=[
    {

    id: 1,
    title: "Google pixel - Black",
    img: "img/product-1.png",
    price: 10,
    company: "Google",
    info:
    "T",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 2,
    title: "samusung s7",
    img:"img/product-2.png",
    price: 16,
    company:"samsung",
    info:"",
    inCart: false,
    count: 0,
    total: 0

    
},
{
    id: 3,
    title: "black berry",
    img:"img/product-3.png",
    price: 16,
    company:"black berry",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
id: 4,
title: "nokia",
img:"img/product-4.png",
price: 16,
company:"nokia",
info:"",
inCart: false,
    count: 0,
    total: 0,
},
{
    id: 5,
    title: "infinix",
    img:"img/product-5.png",
    price: 16,
    company:"infinix",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 6,
    title: "Tecno Spark",
    img:"img/product-6.png",
    price: 16,
    company:"tecno",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 7,
    title: "tecno phantom",
    img:"img/product-7.png",
    price: 16,
    company:"tecno",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 8,
    title: "xiaomi",
    img:"img/product-8.png",
    price: 16,
    company:"xiaomi",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 9,
    title: "huawei",
    img:"img/product-9.png",
    price: 16,
    company:"huawei",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 10,
    title: "iphone x",
    img:"img/product-10.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 11,
    title: "iphone x",
    img:"img/product-11.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 12,
    title: "iphone x",
    img:"img/product-12.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 13,
    title: "iphone x",
    img:"img/product-13.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 14,
    title: "iphone x",
    img:"img/product-14.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 15,
    title: "iphone x",
    img:"img/product-15.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 16,
    title: "iphone x",
    img:"img/product-16.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 17,
    title: "iphone x",
    img:"img/product-17.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 18,
    title: "iphone x",
    img:"img/product-18.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 19,
    title: "iphone x",
    img:"img/product-19.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 20,
    title: "iphone x",
    img:"img/product-20.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 21,
    title: "iphone x",
    img:"img/product-21.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 22,
    title: "iphone x",
    img:"img/product-22.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 23,
    title: "iphone x",
    img:"img/product-23.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 24,
    title: "iphone x",
    img:"img/product-24.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 25,
    title: "iphone x",
    img:"img/product-25.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 26,
    title: "iphone x",
    img:"img/product-26.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 27,
    title: "iphone x",
    img:"img/product-27.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 28,
    title: "iphone x",
    img:"img/product-28.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 29,
    title: "iphone x",
    img:"img/product-29.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 30,
    title: "iphone x",
    img:"img/product-30.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 31,
    title: "iphone x",
    img:"img/product-31.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 32,
    title: "iphone x",
    img:"img/product-32.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
id: 33,
title: "iphone x",
img:"img/product-33.png",
price: 10,
company:"apple",
info:"",
inCart: false,
count: 0,
total: 0
},
{
    id: 34,
    title: "iphone x",
    img:"img/product-34.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 35,
    title: "iphone x",
    img:"img/product-35.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 36,
    title: "iphone x",
    img:"img/product-36.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 37,
    title: "iphone x",
    img:"img/product-37.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 38,
    title: "iphone x",
    img:"img/product-38.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 38,
    title: "iphone x",
    img:"img/product-38.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 39,
    title: "iphone x",
    img:"img/product-39.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 40,
    title: "iphone x",
    img:"img/product-40.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 41,
    title: "iphone x",
    img:"img/product-41.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 42,
    title: "iphone x",
    img:"img/product-42.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 43,
    title: "iphone x",
    img:"img/product-43.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 44,
    title: "iphone x",
    img:"img/product-44.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 45,
    title: "iphone x",
    img:"img/product-45.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 46,
    title: "iphone x",
    img:"img/product-46.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 47,
    title: "iphone x",
    img:"img/product-47.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 48,
    title: "iphone x",
    img:"img/product-48.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},

{
    id: 49,
    title: "iphone x",
    img:"img/product-49.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 50,
    title: "iphone x",
    img:"img/product-50.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 51,
    title: "iphone x",
    img:"img/product-51.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 52,
    title: "iphone x",
    img:"img/product-52.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 53,
    title: "iphone x",
    img:"img/product-53.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 54,
    title: "iphone x",
    img:"img/product-54.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 55,
    title: "iphone x",
    img:"img/product-55.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 56,
    title: "iphone x",
    img:"img/product-56.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 57,
    title: "iphone x",
    img:"img/product-57.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 58,
    title: "iphone x",
    img:"img/product-58.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 59,
    title: "iphone x",
    img:"img/product-59.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 60,
    title: "iphone x",
    img:"img/product-60.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 61,
    title: "iphone x",
    img:"img/product-61.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 62,
    title: "iphone x",
    img:"img/product-62.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 63,
    title: "iphone x",
    img:"img/product-63.png",
    price: 16,
    company:"apple",
    info:"",
    inCart: false,
    count: 0,
    total: 0
}
];
export const detailProduct = {
    id: 1,
    title: "Google pixel-Black ",
    img: "img/product-1.png",
    price: 10,
    company: "Google",
    info: "",
    incart: false,
    count: 0,
    total: 0
};
